title: cornsupply
email: your@cornsupply.cc
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: https://cornsupply.cc
twitter_username: 
github_username:  AlekseyTarasov

# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-feed

# Multilingual
defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "home"
    language: en
- scope:
    path: "ua"
  values:
    layout: "home"
    language: ua
- scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: '/:title'
    language: en
- scope:
    path: '_posts/ua'
    type: 'posts'
  values:
    permalink: 'ua/:title'
    language: ua