title: cornsupply
email: your@cornsupply.cc
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: https://cornsupply.cc
twitter_username: 
github_username:  AlekseyTarasov

# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-feed

# Multilingual
defaults:
- scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'news/:title'
    language: en
- scope:
    path: '_posts/nl'
    type: 'posts'
  values:
    permalink: 'nieuws/:title'
    language: nl